USE AnimalibDB;

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (1, 'Gorilla', '1,75 m', '200 kg', 'Afrika', 'Menschenaffen (Hominidae)', 'Die Gorillas (Gorilla) sind eine Primatengattung aus der Familie der Menschenaffen (Hominidae). Sie sind die größten lebenden Primaten und die ausgeprägtesten Blätterfresser unter den Menschenaffen. Sie sind durch ihr schwarzgraues Fell und den stämmigen Körperbau charakterisiert und leben in den mittleren Teilen Afrikas. Wurden früher alle Tiere zu einer Art zusammengefasst, so unterscheiden jüngere Systematiken zwei Arten mit jeweils zwei Unterarten.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_gorilla.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (2, 'Sibirischer Tiger', '2,30 m', '306 kg', 'Sibirien', 'Katzen (Felidae)','Der Sibirische Tiger (Panthera tigris altaica), auch Amurtiger oder Ussuritiger genannt, ist eine Unterart des Tigers und die größte lebende Katze der Welt.[1] Der Wildbestand beläuft sich heute auf weniger als 500 Tiere, die im Fernen Osten Russlands und angrenzenden Gebieten Nordkoreas und Chinas leben. Die IUCN listet die Unterart als „stark gefährdet“ (Endangered).', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_tiger.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (3, 'Nashorn', '1,8 m', '5000 kg', 'Afrika', 'Unpaarhufer (Perissodactyla)', 'Die Nashörner (Rhinocerotidae) oder auch Rhinozerosse bilden eine Familie der Unpaarhufer (Perissodactyla) mit heute noch fünf lebenden Arten. Sie sind charakterisiert durch einen kräftigen Körper und kurze Gliedmaßen mit drei Zehen sowie einen großen Kopf, der bei allen heute lebenden Vertretern eine markante Bildung, bestehend aus einem oder zwei – für die Familie namensgebenden – Hörnern, trägt.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_rhino.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (4, 'Grizzlybär', '2,5 m', '680 kg', 'Nordamerika', 'Bären (Ursidae)', 'Der Grizzlybär (Ursus arctos horribilis), seltener auch Graubär genannt, ist eine in Nordamerika lebende Unterart des Braunbären (Ursus arctos) aus der Familie der Bären (Ursidae). Ging man in früherer Zeit noch von zahlreichen verschiedenen Unterarten auf diesem Kontinent aus, so werden heute in der Regel alle dort lebenden Braunbären mit Ausnahme der Kodiakbären als Grizzlybären bezeichnet.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_grizzly.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (5, 'Zebra', '3,0 m', '180-350 kg', 'Afrika', 'Pferde (Equidae)', 'Die Zebras (Hippotigris) sind eine Untergattung aus der Gattung der Pferde (Equus), die aus drei Arten besteht: Grevyzebra (Equus grevyi), Bergzebra (Equus zebra) und Steppenzebra (Equus quagga). Die Tiere sind besonders durch ihr schwarz-weißes Streifenmuster gekennzeichnet. Alle Vertreter der Zebras kommen ausschließlich in Afrika vor, wo sie zumeist offene Landschaften bewohnen. Die Bestände der einzelnen Arten sind in unterschiedlichem Maße bedroht.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_zebra.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (6, 'Weißkopfseeadler', '1,2 m', '2,5-6,3 kg', 'Nordamerika', 'Habichtartige (Accipitridae)', 'Der Weißkopfseeadler (Haliaeetus leucocephalus, aus griechisch ἁλι- hali- „meerwasser-“, αἰετός aietos „Adler“, λευκός leukos „weiß“, κεφαλή kephale „Kopf“) ist ein großer Greifvogel aus der Familie der Accipitridae. In Aussehen und Lebensweise ähnelt die Art sehr dem eurasischen Seeadler, die beiden Arten werden daher von manchen Autoren zu einer Superspezies vereinigt. Der Weißkopfseeadler ist der Wappenvogel der USA und daher auf deren Siegel zu sehen.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_eagle.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (7, 'Habicht', '46-63 cm', '0,52 kg', 'Europa', 'Greifvögel (Accipitriformes)', 'Der Habicht (Accipiter gentilis) ist ein Greifvogel, der zur Familie der Habichtartigen (Accipitridae) gehört. Das Verbreitungsgebiet der Art umfasst die arktischen bis subtropischen Zonen der Holarktis. Habichte ernähren sich überwiegend von kleinen bis mittelgroßen Vögeln und Säugetieren bis zu einem Gewicht von etwa 1,0 kg. Die Art ist nicht gefährdet.\r\n\r\nDer Naturschutzbund Deutschland und der Landesbund für Vogelschutz in Bayern haben den Habicht zum „Vogel des Jahres 2015“ in Deutschland gewählt.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_habicht.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (8, 'Alpensteinbock', '1,5 m', '40-100 kg', 'Europa (Alpen)', 'Hornträger (Bovidae)', 'Der Alpensteinbock (Capra ibex) oder Gemeiner Steinbock – zur Abgrenzung von anderen Steinböcken – ist eine in den Alpen verbreitete Art der Ziegen. Ein weiblicher Steinbock wird Steingeiß genannt.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_alpensteinbock.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (9, 'Weißer Hai', '4,0-7,0 m', '200-400 kg', 'Afrika, Nordamerika', 'Makrelenhaiartige (Lamniformes)', 'Der Weiße Hai (Carcharodon carcharias), seltener auch als Weißhai oder Menschenhai bezeichnet, ist die einzige Art der Gattung Carcharodon aus der Familie der Makrelenhaie (Lamnidae). Der Trivialname bezieht sich auf die auffällig helle Bauchfärbung der Tiere. Die Art kommt fast weltweit vor und besiedelt bevorzugt gemäßigte Küstengewässer. Als die größte Haiart, die sich nicht von Plankton ernährt, ist der Weiße Hai der größte Raubfisch; er kann auch Menschen gefährlich werden. Er ist im gesamten Verbreitungsgebiet selten; heute gilt er durch Beifang in der kommerziellen Fischerei sowie gezielte Bejagung zum Gewinn von Trophäen als im Bestand bedroht.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_shark.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (10, 'Eisbär', '2,0-2,5 m', '150-300 kg', 'Arktis', 'Bären (Ursidae)', 'Der Eisbär (Ursus maritimus), auch Polarbär genannt,[1] ist eine Raubtierart aus der Familie der Bären (Ursidae). Er bewohnt die nördlichen Polarregionen und ist eng mit dem Braunbären verwandt. Neben Kamtschatkabären und Kodiakbären gelten Eisbären als die größten an Land lebenden Raubtiere der Erde.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_icebear.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (11, 'Vogelspinne', '12 cm', '480 g', 'Südamerika, Asien', 'Spinnentiere (Arachnida)', 'Die Vogelspinnen (Theraphosidae) sind eine Familie in der Unterordnung der Vogelspinnenartigen (Mygalomorphae) innerhalb der Webspinnen (Araneae) und umfassen 146 Gattungen und 979 Arten, die sich auf 12 Unterfamilien verteilen.[1] (Stand: Dezember 2018). Vogelspinnen traten bereits im Karbon vor 350 Millionen Jahren auf. Ihr Lebensraum sind vorrangig tropische bis subtropische Klimazonen. Umgangssprachlich werden unter dem Begriff „Vogelspinnen“ manchmal auch Vertreter anderer Vogelspinnenartigen bezeichnet.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_tarantula.jpg', SINGLE_BLOB) as Image));

INSERT INTO Animals (Id, Name, Height, Weight, Regions, Species, Description, Image) 
VALUES (12, 'Nilkrokodil', '3,0-4,0 m', '300 kg', 'Afrika', 'Echte Krokodile (Crocodylidae)', 'Das Nilkrokodil (Crocodylus niloticus) ist eine Art der Krokodile (Crocodylia) aus der Familie der Echten Krokodile (Crocodylidae). Die normalerweise 3–4 m lang werdende Art bewohnt Gewässer in ganz Afrika und ernährt sich größtenteils von Fischen. Gelegentlich können Nilkrokodile jedoch auch große Säugetiere (z. B. Zebras) unter Wasser zerren und ertränken. Das Nilkrokodil betreibt intensive Brutpflege, die Mutter bewacht ihr Nest und beschützt die Jungtiere in den ersten Lebensmonaten. Die Art nahm eine wichtige Rolle in der ägyptischen Mythologie ein und war einst wegen starker Bejagung gefährdet. Nachdem die Jagd in den 1980ern verboten wurde, haben sich die Bestände weitgehend erholt.', (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\images\animal_crocodile.jpg', SINGLE_BLOB) as Image));